### ISSUE TITLE
Can't register, and no details given about failure

### ISSUE THREAD

**Issue by JC3** [userstyles-world/userstyles.world#108]
When I try to register, and receive the verification email, clicking the link in the email yields:

![image](https://user-images.githubusercontent.com/5651184/152894499-8952c375-ad43-4782-a976-5476f279df5d.png)

I also tried registering via my GitHub account but clicking the GitHub button yields:

`{"data":"Internal Error."}`

So not really sure how to proceed.

Chrome, Windows, AdBlock disabled.

**Comment by JC3** [comment]
I'll try again tomorrow and update here; perhaps it's temporary (although I'd expect a 503 somewhere; I didn't check response headers though).

**Comment by vednoc** [comment]
I may have forgotten to run a database migration after deploying https://github.com/userstyles-world/userstyles.world/commit/51b0faa5065e90272845787beaae46a0b2a1187e... I'm so sorry about that. Looking at the logs, I counted 21 failed registrations because of a missing database column. After performing the migration and making a new account, I can confirm that the issue has been resolved.

Thank you so much for bringing this issue to my attention.

**Comment by JC3** [comment]
I can confirm that all is good now. Registered via GitHub.

Thanks for looking into that so quickly!

**Comment by JC3** [comment]
PS The font size on that "registration failed" message is soul-crushingly large, haha.

**Comment by vednoc** [comment]
Oh, indeed! Looks like our `err.html` template uses the same `Hero` class that we use on the landing page. 😅 On a related note: I've been thinking of a better way to manage alerts, since we should have more of them coming in the future.
