### ISSUE TITLE
Allow Image Hosted on Github Gist to be a Preview

### ISSUE THREAD

**Issue by XiaoPanPanKevinPan** [userstyles-world/userstyles.world#115]
**Describe the change you'd like**:
As mentioned in the title, I hope it'll be possible to use a URL of "gist.githubusercontent.com" as the Preview image URL on the style's Edit page.

**Additional context**:
When I was trying to add a preview image for [my style]( https://userstyles.world/edit/4877 ), I saw the limitation "External images must be hosted on GitHub.com, ...". Therefore, I created [a gist]( https://gist.github.com/XiaoPanPanKevinPan/fa306bb96c2c6159e4dd56866d143bda ) and managed to upload a .webp file onto it. But when I was pasting [the URL]( https://gist.githubusercontent.com/XiaoPanPanKevinPan/fa306bb96c2c6159e4dd56866d143bda/raw/46ec18610cb1191d1a2a0720b64988af3279d5f7/discordMinimizeSidebars_preview.webp ), I just got an error.

**Comment by vednoc** [comment]
I deployed the changes and you should now be able to use the "gist" subdomain. However, keep in mind that we don't support animated images at the moment. If you'd like to showcase an animated image, please embed it using Markdown in the notes section (since description section isn't meant for that purpose).
