### ISSUE TITLE
Search using terms on the category property

### ISSUE THREAD

**Issue by Gersonzao** [userstyles-world/userstyles.world#128]
**Describe the change you'd like**:
I wish that when I searched for a **website** [e.g. google.com instead of just Google] it looked for the styles' category property

**Additional context**:
None

**Comment by Gersonzao** [comment]
It's related to the second paragraph of your first reply, specifically

**Comment by vednoc** [comment]
This was fixed in [f979273](https://github.com/userstyles-world/userstyles.world/commit/f9792732dbc53fe51e7354e63645bf46a9c3b09b), then improved in [f5e0dd9](https://github.com/userstyles-world/userstyles.world/commit/f5e0dd988893a795bb2c1ce195e141eeed1ff31d) to take into account a couple of edge-cases.
