### ISSUE TITLE
Lost many Screenshots of userstyles when i refresh the profile page

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#131]
I used to stay on my Profile page to see the evolution of install..

As the title said, after a refresh, many screenshots are blank.

Or the page became like their are no CCS (strange presentation)..

Can you correct that?
![USERSTYLES WORLD - PB refresh - Small - 2022-10-29_113003](https://user-images.githubusercontent.com/868778/198824567-f193dadd-3764-48bc-b266-9ff1f1159c31.jpg)

**Comment by vednoc** [comment]
We had someone flood our server with requests, so I ended up making our rate limiter more strict in case banning the IP addresses wasn't good enough. As a result, some images didn't load. Should be fine now. 

P.S. Since I saw you on Stylus' Discord, you want want to join our Discord as well for live updates.

**Comment by decembre** [comment]
Thanks!
But yet .... always lost screentshots (i clear my cache too).

Note:
If you change the way of sorting choice (keep our last choice) it should possible to just click on profile to have a similar result to an refresh.
In a same direction:
Why have to choice a sort and after click on "Sort" button?
I prefer save a click to have the function..
Yes, i know, i am lazy :-)

About our Discord Channel:
I found it useful to have fresh info, but i don't use it to much because i am not so familiar with its Markdown flavor...

**Comment by vednoc** [comment]
Alright, I've rewritten the rate limiter once again. It was a misconfiguration because the way it works isn't particularly intuitive. Could you confirm that you have no more issues with it?

> keep our last choice

We might have that in the future. I'm just not sure how we would implement it.

> Hoo, and the field should reflect our choice...

That should be a bug. I'll look into it.

> Why have to choice a sort and after click on "Sort" button?

We don't use JavaScript to automatically do it for you.

> i am not so familiar with its Markdown flavor

Plain text is sufficient. Besides, Discord has a live preview of Markdown should you decide to use it, but that wasn't my point.

**Comment by decembre** [comment]
Good work:
i confirm, no more issues with it.
And for the rest, as usual, i know you work on it.
