### ISSUE TITLE
Cannot upload a style to the site, reports that I left various fields empty, but they're filled in.

### ISSUE THREAD

**Issue by creedorofl** [userstyles-world/userstyles.world#133]
I've tried uploading a new style to userstyles.world... both from this popup window generated from the Stylus plugin, and directly from desktop Windows 10 Chrome Version 107.0.5304.107 (Official Build) (64-bit).

I fill in all the blanks except two: I don't have a homepage, and I leave the license blank because it says a license will be chosen for me if I leave it blank.

After filling in all these blanks and uploading a screenshot (which is under 200kb if it matters), I get three errors -

@name field cannot be empty  
@namespace field cannot be empty  
@version field cannot be empty

I tried the import feature on the website, but it only seems to accept imports from two sites, and one of them changed the link. Neither of the sites has mirrored my userstyle (yet). 

I tried in incognito mode to make sure all plugins are disabled, so no plugin is causing this.

Are these missing field errors based on the actual fields on the upload page? Or are they maybe based on some fields from elsewhere? Or info that needs to be in the CSS itself?

![userstyle_err](https://user-images.githubusercontent.com/67012973/202303256-9d404c8e-295b-4d4b-a363-bb9ad76c3a7a.png)

**Comment by vednoc** [comment]
Problem is in the CSS: it's not valid right now because it's missing [UserCSS metadata][1]. Just in case, you might run into an issue with [bad style format][2] that we had a long time ago depending on how you tried to add it manually. If you don't want to go through the documentation in the first link, have a look at [UserStyles.world Tweaks][3] and compare it to your code. I apologize for the error not being clear as to where things went wrong—we will make it better.

[1]: https://github.com/openstyles/stylus/wiki/Writing-UserCSS#usercss-metadata
[2]: https://userstyles.world/docs/faq#bad-style-format-error 
[3]: https://github.com/userstyles-world/tweaks/blob/main/tweaks.user.styl

**Comment by vednoc** [comment]
> [...] and one of them changed the link.

Could you share the links? We might also want to look into relaxing the rules. I was, perhaps, just being too wary.

**Comment by creedorofl** [comment]
ah ok, sorry if I missed something covered in the documentation. I suspected it was the code and shoulda followed up on that.

The import page provides two links that are supposed to mirror userstyles.org. 

https://33kk.github.io/uso-archive/ - this is the broken link
https://uso-archive.surge.sh/ - this works

Is it not possible to import from userstyles.org directly? Although the site is said to be abandoned, uploading still works and I got my style on there. Maybe others have recently uploaded before realizing "oh, there's nobody steering this ship".
