### ISSUE TITLE
Unable to register/login

### ISSUE THREAD

**Issue by SethFalco** [userstyles-world/userstyles.world#160]
- **Browser**: Firefox 111.0.1 (64-bit)

- **Screenshot**:

![image](https://user-images.githubusercontent.com/22801583/230597890-7be10c6a-9a37-4b07-9bda-bcc38ed00e5d.png)
> When I try to register/login with GitHub or GitLab. I have to clear cookies to get away from this page.

![image](https://user-images.githubusercontent.com/22801583/230598025-b08146a1-d01f-421a-8d0b-a1018bbc1b57.png)
> When I try to verify the email on an account created with email/password.

- **Additional context**:

1. I attempted to register via email/password, but after 10 minutes I still didn't get a verification code.
2. I opted to login with GitHub instead to bypass this, which worked.
3. Then I did receive the verification code… so I thought I'd just delete the account created with oAuth and remove the application from GitHub and go through the normal email/password route.
4. Verification doesn't work.
5. If I try to create an account again, it fails to verify.
6. If I try to oAuth with GitHub or GitLab again, it logs me in but I just see "User not found".

At this point, I am no longer able to use the website with any of the authentication methods.

**Comment by vednoc** [comment]
This is because we use soft deletion by default and you ran into an edge-case that isn't handled yet. Why soft deletion? Because I'd like to make sure we don't end up removing user data by accident. Account deletion was added pretty recently, so it might be in a bit of a rough shape ATM.

I've deleted your user account and OAuth data manually. You should be able to sign up again. I'm not sure why that email took over 10 minutes to arrive, but I'll keep an eye on our email server. BTW, it's the "verification code" itself that contains all the data for creation of your account—we don't create an account beforehand.

**Comment by SethFalco** [comment]
> I'm not sure why that email took over 10 minutes to arrive

I'm not sure either, but it could be it was just a hiccup somewhere, i.e. my mail provider.
The first email took 10 minutes to arrive, but all subsequent attempts to register took < 60 seconds.

Meanwhile, I understand. Thanks for the context and for manually resolving my case for me!

**Comment by vednoc** [comment]
> I'm not sure either, but it could be it was just a hiccup somewhere, i.e. my mail provider.

It could also be on our end since we use a self-hosted email server. Performance-wise, it [looks pretty normal to me](https://userstyles.world/grafana/public-dashboards/f75cfb0752a843098c03c97283885cf1).

> Thanks for the context and for manually resolving my case for me!

Thank you so much for bringing this to my attention. I'll give it a bit more time before we start deleting records permanently.

P.S. Welcome aboard! 🎉
