### ISSUE TITLE
Make Imported Userstyles auto updatable when an update come to the original source?

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#19]
After i import an userstyle , it should be great if i can choose to rely it (or not)  to its USO version.
If an update come on it, it self update its CSS code (and maybe the description too).

The idea is that can became difficult to maintain an usertyles through many different places i test:
I post to Usertsyles.org, Greasyfork and test here now....
:-)

**Comment by vednoc** [comment]
Since there is no way to check for updates, it would have to be done periodically (every 12/24 hours). Right now you can replace the source code with install URL and it will redirect to your userstyle hosted in USo-archive. For reference, see source code block for Dark-GitHub userstyle: https://www.v1.userstyles.world/style/1

As for description (and/or other fields), that's a tricky one. It would have to be optional because _importing_ is not the same as _mirroring_, so we would need extra logic for this to work.

**Comment by decembre** [comment]
Seems the good way.
"Auto update" should  be optional for CSS and description:
Maybe one day, we never use Userstles.org....
;-)

**Comment by vednoc** [comment]
Hey @decembre, just wanted to let you know that you'll have to sign up once again on https://userstyles.world/ because we deleted the old database due to amount of changes in how things work now. Most of the features/issues that you asked for and/or reported have made it in, and I'd love to hear what you think when you give them a try.
