### ISSUE TITLE
Not receiving email verification on Tutanota

### ISSUE THREAD

**Issue by Freeplayg** [userstyles-world/userstyles.world#29]
- **Browser**: Firefox 87.0 (64-bit)
- **Additional context**: Signing up using a @tutanota.com domain doesn't send the verification email (Not in spam either). Tried using Protonmail instead and it ended up in my spam.

**Comment by Gusted** [comment]
Hi @Freeplayg!

After several tries to get an account signed up on Tutanota, I didn't got any account.
However I found some interesting links:
https://tutanota.com/blog/posts/website-blocks-secure-email-tutanota/ (We don't block any domain)
https://www.reddit.com/r/tutanota/comments/l8vvjq/not_receiving_email/glfcflh?utm_source=share&utm_medium=web2x&context=3

Regards,
Gusted

**Comment by vednoc** [comment]
This issue is now confirmed to be resolved. For posterity, the problem was with reverse DNS configuration at our hosting provider.

Side note: another service that failed to receive confirmation e-mails is OVH, but that's all I gathered from e-mails that failed to be delivered. Now to figure out why it goes to spam. 😅
