### ISSUE TITLE
Add more userstyles

### ISSUE THREAD

**Issue by slaeprop** [userstyles-world/userstyles.world#3]
On the website there are only 8 styles, will there come more?

**Comment by vednoc** [comment]
More will be more soon. I'm figuring out a slightly better scheme for [userstyle template][1], and after that I'll add a few more userstyles that I use. It's a manual process, so doing everything on my own gets kinda tedious. You can find more userstyles by searching with [usercss][2] or [userstyle][3] tags.

I'd love if more userstyles were being contributed.

[1]: https://raw.githubusercontent.com/vednoc/userstyles.world/main/archetypes/userstyle.md 
[2]: https://github.com/topics/usercss
[3]: https://github.com/topics/userstyle

**Comment by vednoc** [comment]
I apologize for the ping, but I have no better way of reaching out to everyone listed below.

Since USw has been rewritten, all previous userstyles are now removed. I'm looking for feedback on what can be improved, changed, fixed, etc. At the moment, you can register/login, explore all userstyles, and add/import/edit/delete your userstyles like on USo. For userstyles that haven't been converted to UserCSS format, they're available in the [USo-archive][1].

Keep in mind that this is the very first public beta. Check the [Roadmap][2] for an incomplete list of tasks, and feel free to open a new issue if you have feature requests. More features are coming soon.

The rewrite is live at: https://www.v1.userstyles.world

Cc: @AbhayAysola @Barina @RaitaroH @the-j0k3r @Verticablets

[1]: https://33kk.github.io/uso-archive/
[2]: https://github.com/userstyles-world/userstyles.world/projects/1

**Comment by the-j0k3r** [comment]
> For userstyles that haven't been converted to UserCSS format, they're available in the [USo-archive](https://33kk.github.io/uso-archive/).

uso archive converts all styles to usercss by adding the usercss header so they can be directly installed via the site, which then bypasses all author support/updates.

**Comment by vednoc** [comment]
> uso archive converts all styles to usercss by adding the usercss header so they can be directly installed via the site, which then bypasses all author support/updates.

@the-j0k3r That is not how it works. You can import your userstyle and edit it directly from USw. USo-archive is convenient because it already did the work of converting "traditional" format to UserCSS format.

Here's what your userstyle would look like if I imported it from my account. You can also replace source code with install URL for your UserCSS styles on GitHub, and USw will redirect to it after clicking on install button, so you don't ever have to update the code on USw. This will prevent you from getting "userstyle analytics", but that functionality is still on to-do list.

![image](https://user-images.githubusercontent.com/18245694/111457809-f4259280-8718-11eb-8c48-29832fee567b.png)

**Comment by the-j0k3r** [comment]
I meant uso archive makes everything usercss,

**Comment by vednoc** [comment]
I left out license field for that reason, but it should be added in the next beta release. I'll also add a note about it on edit page.

**Comment by the-j0k3r** [comment]
> I left out license field for that reason,

The license is the most important, people know that they can freely edit and share their work is important. Not knowing the license or having the license mangled by any website is both weird and weirder.

**Comment by vednoc** [comment]
It's in beta, and there is 1 (one) userstyle that isn't mine for the 38 hours the website has been running. Make out what you will out of that data. Besides, you can see that field in the source code, unless the userstyle redirects to external userstyle (which is the case for 3 out of 4 of my userstyles).

**Comment by vednoc** [comment]
@the-j0k3r

The next release will have full support for license fields.
