### ISSUE TITLE
Seems the auto Update don't work for a scrennshots change

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#37]
Tha auto update from USO work fine for CSS code.
But don't update screenshots change and Notes ( not tested for Description).

**Comment by vednoc** [comment]
We're only mirroring source code at the moment. I'm thinking of how to implement mirroring of other fields, so that we don't accidentally remove content that has been set already. Perhaps we should have another checkbox for mirroring of userstyle name, preview image, description, and notes. What do you think?

**Comment by decembre** [comment]
Checkbox should be great.
:-)
