### ISSUE TITLE
Userstyle weekly/total install counters

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#45]
We need a counter for install on USw.
But before implementing it, can you add the install infos from USO too ?
And Update it regularly if it is possible ?

**Comment by vednoc** [comment]
I posted this on Discord roughly around the same time you opened this issue. Install counters from USo won't be added simply because we're starting from scratch. There are also other reasons for that, so this seems a lot more fair towards everyone.

![SQLite Browser tables with statistics](https://media.discordapp.net/attachments/827600537171656705/830529318584057896/unknown.png)
