### ISSUE TITLE
Add style statistics

### ISSUE THREAD

**Issue by RiedleroD** [userstyles-world/userstyles.world#46]
I think a very important part of hosting styles would be providing some kind of statistics system. I think a nice roadmap would include:
- [x] installations per style
- [x] views per style
- [x] the above, but for the whole site
- [x] the above, in the last month (or 28/30 days)
- ~~style ratings (maybe thumbs up/down, or a star rating system)~~
-  ~~comments~~
- [ ] sorting styles by all of those metrics (and lines of code maybe)

I know most of this is still far into the future, but I wanted to hear your opinion on those ideas, as well as provide some ideas for the future.

**Comment by vednoc** [comment]
As referenced in #45, we have total and weekly installs coming in the next release. I'm be adding views as well, figuring out the logic for it ATM. 

3 and 4 could (easily) be calculated from stats: both site-wide stats, as well as per-author stats.

5 and 6 are separate issues. Comments (or reviews) feature is probably one of the last things we'll implement since we need more users and userstyles for it to actually be useful. I would like it to be optional because most authors (including myself) prefer using proper bug trackers.

7 was briefly mentioned in #42. I'll look into implementing it after the next release.

**Comment by RiedleroD** [comment]
Thanks for the reply & sorry I didn't read the other issues. Should've done that. I'm going to leave the issue unclosed & update its checkmarks when needed if that's ok with you.

**Comment by vednoc** [comment]
It's all good. We do have a small backlog of issues to go through. 😄

I got views figured out, might do the site-wide stats next and put them on the landing page or something like that. Also updated the checkmark by clicking on it! Small preview of current style statistics:

![image](https://user-images.githubusercontent.com/18245694/114450062-d4797100-9bd5-11eb-82b3-fc007eed2274.png)

**Comment by decembre** [comment]
Can you add too a "Stats Keeper" function?.

Previously i used an old userscript for userstyles.org (Broken: not updated since a long time...):
<a href="https://userscripts-mirror.org/scripts/show/80666">Userstyles.org Enhancer</a>

It provided the diff from the last view.
"Shows you the increase/decrease in style statistics from your last visit.":
It was very informative to follow my stuffs.

**Comment by vednoc** [comment]
> "Shows you the increase/decrease in style statistics from your last visit.":

We would somehow have to store last visit and exclude using our API for it to be accurate. Also, we will need to take daily snapshots for our statistics because we're not doing that ATM. @Gusted Thoughts?

**Comment by RiedleroD** [comment]
I'm not sure how the userscript is doing it, but storing the info in a cookie would probably be much more efficient. No need for snapshots in that case.

**Comment by vednoc** [comment]
Snapshots would save daily installs/visits, so that we can get a similar graph to the one that USo provides without having to sort through a ton of "garbage" data in Stats table.

Right now we are saving a unique record that's composed of user's IP plus style ID, that is then hashed ([source][1]) before inserting to Stats table. We make use of `updated_at` field for calculating number of installs in the last week/month/etc. I wanted to add shapshots anyways, because that is a must in order to get the data for aforementioned graph.

[1]: https://github.com/userstyles-world/userstyles.world/blob/96e46d8c48/models/stats.go#L43-53

**Comment by vednoc** [comment]
Referenced the wrong issue. That's what happens when sleepiness kicks in. 😅
