### ISSUE TITLE
Add an install button for the "old" userstyle format

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#49]
I can't install Usercss with Stylus and Waterfox Classic, du a bug on Waterfox it seems:

I posted about that in both place:
<a href="https://github.com/MrAlex94/Waterfox/issues/2040">Stylus Addon + Waterfox Classic : can't install Usercss ? [Waterfox]</a>
<a href="https://github.com/openstyles/stylus/issues/1220">invalid regexp group [Stylus Addon]</a>

So, add a way to install too with Stylish and the old userstyle formating solve that.

In an other hand , many users use the Stylish Addon and don't take care to Usercss format too.

If this function is added, it should be a way to assure a retro compatibility too and expand the usage of the site.

**Comment by Gitleptune** [comment]
wha

**Comment by Gusted** [comment]
> wha

Yeah this, So there is a bug on waterfox because it doesn't have the look-behind regex which stylus uses to parse the usercss-meta. So this is a feature request to strip the usercss meta and just serve the raw CSS(with moz-domain specifier)?

**Comment by decembre** [comment]
<blockquote>So this is a feature request to strip the usercss meta and just serve the raw CSS(with moz-domain specifier)?</blockquote>:
yes!

**Comment by Gusted** [comment]
> : yes!

Few problems I have with such approach, what to do with options that are included within such usercss? And what does this benefit I've rjust copy pasting the part of the code.

**Comment by decembre** [comment]
<blockquote>And what does this benefit I've just copy pasting the part of the code</blockquote>
More transparent and easy for the whole users.
Maybe add too a "?" which explain the problem about options?

**Comment by Gusted** [comment]
Transparent? Please elaborate?
Easy for the whole users? Who are these "whole users"



> Maybe add too a "?" which explain the problem about options?

"Yeah so, install it the old fashion way. But it won't really work, because some values are options and so you need to replace it with correct code. Have a nice day!" I don't really see what's the ease of this.

**Comment by decembre** [comment]
<blockquote>Easy for the whole users? Who are these "whole users" ?</blockquote>
Yes.. a normal, not experimented, newbie user?
Haa my english ....

<blockquote>I don't really see what's the ease of this.</blockquote>
If "the old fashion way" don't bring the whole functions (options) it can be installed and tested.

It is useful for Waterfox users.
And as i said, many old and new usertyles don't use options:
Mine by example (yet, but maybe later...)

With the bug of Waterfox Classic (my principal browser),
I can't test the install of any Usercss process.
Actually just the old format work with it.

The install "As usestyle" from my Greasyfork version fail too,
but "As userscript" work.
Maybe an approach to solve my "little problem"...

But .... Yes .... we can live without:
Use another browser,
or Copy/ Past etc....
Less easy.

Anyway, as usual, thanks for your attention and hard work for us.
Good week for you too.

Notes:
I am not certain:
Copy / paste just the CSS part of an Usercss with options, is ok ,
and work as default (without  customisation) ?

**Comment by Gusted** [comment]
> Yes.. a normal, not experimented, newbie user? Haa my english ....

I see what you meant, just your [Average User/Joe](https://en.wikipedia.org/wiki/Average_Joe).


So you currently cannot install any UserCSS due to the meta that's include because stylus uses an non support regexp for the meta. And as workaround an button that just gives the CSS without any meta. 

So, we include the source code of the style on the style's page so you can anyway just copy paste that without having to use another browser. The one concern I have is that it won't work for a lot of Styles. As, old fashion/traditional  CSS -> UserCSS is an easy conversion. However for UserCSS -> old fashion CSS is a whole new subject. 

Let's take an example dark-github from @vednoc https://userstyles.world/style/2
You can see the source code within the page and should be able to copy and paste just the CSS part into a new "style". Problem is if you look at the CSS, it's another CSS language and still won't work, just UserCSS can define preprocessers that later on will be converted to normal CSS.

A lot new Styles have such language and a easy button to just show the CSS isn't really possible, because it should be converted to normal CSS with default settings and later on remove the UserMeta well hoping it didn't f*ck anything up within the CSS itself.

**Comment by decembre** [comment]
<blockquote>I see what you meant, just your Average User/Joe.</blockquote>:
Yes, "Joe Schmo" ...
:-)

<blockquote>However for UserCSS -> old fashion CSS is a whole new subject.</blockquote>:
Yes, seems too complicated for a little benefice.

And as you said:
The CSS code is here and i have fingers.
I am too lazy said my mother...

**Comment by vednoc** [comment]
> So, add a way to install too with Stylish and the old userstyle formating solve that.

This is impossible given our current circumstances: in order to install with Styl*ish*, they would have to implement such functionality on their own. Unlike Sty*us*, which has the ability to install styles from anywhere, Styl*ish* is tied to USo as style "provider" of sorts.

There is nothing that we can do, and even if there was, the philosophy behind this project doesn't align with the philosophy behind the company that purchased USo/Stylish, turned it into data mining operation, and went silent on everyone.

> In an other hand , many users use the Stylish Addon and don't take care to Usercss format too.

Most of them don't know about Stylus to begin with. Most of them are also children, which is my assumption based on most popular userstyles on USo. Speculating about this is hard without data, and I do have the data from USo-archive, but it doesn't change the fact that a lot of people "moved on" from userstyles altogether.

> If this function is added, it should be a way to assure a retro compatibility too and expand the usage of the site.

This function could only be added for a subset of styles. ATM, and I'm not 100% sure since I haven't looked into it, but a lot of userstyles on USw are written with more than one customizable option. Many of them use [Stylus-lang preprocessor][1] in place of CSS. So, the subset of styles that can be converted are styles like yours: styles with no options and default USo preprocessor.

Even so, there is basically no point for us to implement this because of the following data:
- Out of 1300 or so unique visitors (let's say 300 are bots, just for the sake of easy math), only 3 (yes, three) use Waterfox Classic. That is 0.3% per 1000.

Therefore, I would rather wait for it to be fixed in Stylus than to spend time implementing a custom solution; time that could be spent on other issues that affect significantly more than just 3 visitors.

> And as i said, many old and new usertyles don't use options:

Userstyles that use traditional format are NOT installable without direct support by the extension. We would have to modify your traditional format into UserCSS format when you click on install button, so that you can install it, but then you wouldn't be able to install it because of your browser. So, it's a no-go.

> but "As userscript" work.

Maybe you could write a userscript to do this for you? Actually, that is probably the best solution to this problem! You could inject a new button and add a function to it that copies source code, removes UserStyle metadata, and copies it to your clipboard. After that is done, you would create a new style and import Mozilla Format, or something along those lines. While it's not convenient, that's the price you'll have to pay for using an old browser. At least, for the time being.

[1]: https://stylus-lang.com/

**Comment by decembre** [comment]
Thanks for the detailed explanation, i understand better the difficulty and the fact it is not trivial to solve this problem for 3 users (include me, the  "Joe Schmo" of the team...).
;-)
