### ISSUE TITLE
Import styles from userstyles.org

### ISSUE THREAD

**Issue by Ryu1845** [userstyles-world/userstyles.world#51]
**Importing userstyles.org styles**:
Someone made an archive of the content of userstyles.org, I think it would be a good idea to import it
https://github.com/33kk/uso-archive

**Comment by Gusted** [comment]
We currently provide such feature within USw, https://userstyles.world/import

**Comment by RiedleroD** [comment]
I think he meant to import all of them in bulk. I'm not sure if that's necessary since backups already exist, and most of them aren't that good anyways and/or were broken by updates to the site they're trying to style.

**Comment by Gusted** [comment]
> I think he meant to import all of them in bulk.

Ah, yeah that's not possible. We aren't some archive. We are a new replacement for USo well we have the option to import the style from USo to us.

**Comment by vednoc** [comment]
On the surface, this does look like a good idea, but when you look deeper into it you quickly realize it's actually not a good idea for multiple major reasons:

1. Like Gusted said, our goal is to be a replacement for USo. Authors that had styles on USo can import them via import page with ease. If they _still_ want to use USo, we have options to enable mirroring of both the source code as well as the style metadata. USo-archive has been a tremendous help thus far, and it does a great job with archiving userstyles from USo.

2. Then there is the problem of not being able to reclaim accounts from USo, so if we imported all userstyles they wouldn't be editable. Implementing logic for verifying authors from both platforms would be unnecessarily complex. There is not a good way to go about this, but at least our import functionality should resolve that issue in its entirety.

3. The last, and probably the most important reason: dead/outdated/garbage styles. While we could import selectively (i.e. styles updated in the last year), it wouldn't be accurate because many sites haven't changed their look in years. Also, many userstyles updated in said period could now be broken due to how fast things change for various sites.

To conclude, I would keep things as they are. For the most part, there is no point in having the same data in two places, so USo-archive has a complimentary role for authors that are switching/mirroring their userstyles from USo to USw.

**Comment by Ryu1845** [comment]
Thank you for the complete answer, I understand.
