### ISSUE TITLE
Links shouldn't be case sensitive

### ISSUE THREAD

**Issue by Freeplayg** [userstyles-world/userstyles.world#56]
https://user-images.githubusercontent.com/40742947/116491563-28d45000-a868-11eb-9fb6-efcaa14882e1.mp4

**Comment by vednoc** [comment]
Had to wait until this was fixed and deployed to production.

Due to a few reasons, one of them being the database we're using and another being the ORM we're using to interact with it, we opted for a way to use lowercase for all usernames and allow users to customize a "display name" however they like. The display name will be implemented in the next release, but for now I had to manually update all usernames that had one or more uppercase characters.

The main reason is this: unique fields are case-sensitive by default, and as such, we could have ended with accounts like freeplay, FrEePlAy, and so on. There is a way to have to make unique case-insensitive fields, but technical reasons prevented that and this was a lot less confusing and better fix to this issue.
