### ISSUE TITLE
Don't save my choice, when i want enable "Mirror source code" and "style metadata" updates

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#60]
Don't save my choice, when i want enable:
_Mirror style metadata (only for styles from USo-archive)_
_Mirror source code updates_
Message on the title textarera:
"Modifier la valeur pour correspondre au format demandé"
That's about an imported userstyle:
<a href="https://userstyles.world/style/140/t-l-rama-voir-notes-sans-inscription-v-1">Télérama - Voir Notes (Sans Inscription)</a>
At the import, no way to choose "Mirror Update" (just the le mention of it).

**Comment by Gusted** [comment]
> Don't save my choice, when i want enable:
> _Mirror style metadata (only for styles from USo-archive)_
> _Mirror source code updates_

As it's a per-style choice and currently indeed not being saved.

**Comment by decembre** [comment]
I don't understand....

**Comment by vednoc** [comment]
This is because we only allow `a-zA-Z0-9!@#$%-_ ` characters in the userstyle name. @Gusted I think it's about time we discuss how to go about this, so that we can avoid having similar issues in the future.

@decembre I tried it locally and, for the time being, you can fix this by replacing `Télérama` with `Telerama`.

**Comment by decembre** [comment]
Thanks for the infos!
