### ISSUE TITLE
Counters reset to 0.....

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#65]
As the title said:
Seems all counters reset to 0, no?

**Comment by vednoc** [comment]
After my recent work on statistics, the data we previously had was incompatible. I let it stay like that for some time, thinking that it would balance itself out, but it didn't. Starting anew, while unfortunate, is necessary in order to get rid of our current hacks (that merge the previous and the current statistics) and make sure statistics are as accurate as possible.

It was my first time building a system like this entirely from scratch. I used premature optimization in the previous version, thinking about performance in the long-run once we get over 100k records in statistics and histories table. That ended up causing inaccuracy of the data being stored because I didn't know what I was doing at the time.

Letting the numbers speak: out of 19k records, 11k of them were affected in one or two ways (for installed and/or viewed stats, which in turn caused issues with updated stats as well). The rest of it is either the new data (for the most part) or the data from returning users, and it works as intended.

**Comment by decembre** [comment]
Ok, maybe can you put an a info in the pages about that ? 

>  is necessary in order to get rid of our current hacks (that merge the previous and the current statistics) and make sure statistics are as accurate as possible.

Hmmm, merging statistics inside USw only or USw and USarchive?
Note:
That's why styles can have more installs than view  ?

Now you rework the statistics, some request about:
1 -  Can you add a "stats Keeper" to them?.
"Stats Keeper":
A number after each stat , like (+1) or (-5) which give the difference after our previous view  or login,
with an option to reset it when we want. 

2 - Add the year to the Created Date in Styles Cards:
Now, it's not confuse (your site is young), but after - i hope it can run many years - it can became confuse.

**Comment by Gusted** [comment]
> That's why styles can have more installs than view ?

No, that's something otherwise. Because @vednoc has his `Dark-XXX` styles on github before USw, he now changed the `updateURL` to the USW one and basically every user that auto-updates will be counted for that statics without ever seeing the style's page. 

With the upcoming Stylus beta, people can download styles from the USw without every having to seen the view page. So you can probably see a lot more styles going into that direction.


> A number after each stat , like (+1) or (-5) which give the difference after our previous view or login,
with an option to reset it when we want.

You mean something for on the dashboard? So that style creators can see how much growth all there styles made since the last time of logging into USw? Actually sounds like a good idea in my ears.

> 2 - Add the year to the Created Date in Styles Cards:
Now, it's not confuse (your site is young), but after - i hope it can run many years - it can be confuse.

You can currently hover over the 3 elements to see more information. The date has an exact time when it was created, down to the second.

**Comment by decembre** [comment]
Thanks for the fast reply, your dogs (your dear code typing collaborators... )  don't sleep!
:-)

<blockquote>upcoming Stylus beta, people can download styles from the USw without every having to seen the view page</blockquote>

Maybe add these "outside install" to the number of views should less confused for others user which don't know the story and they can think there is a problem with stats?

<blockquote> So that style creators can see how much growth all there styles made since the last time of logging into USw? Actually sounds like a good idea in my ears.</blockquote>

Fine, it is in the To Do list ?

> currently hover over the 3 elements to see more information

Ha, i haven't notice that.
But for the short place it take, show the year is more simple (in futur).

**Comment by Gusted** [comment]
> Maybe add these "outside install" to the number of views should less confused for others user which don't know the story and they can think there is a problem with stats?

That isn't really possible without going to remember each IP's visit of paths. Which is something I really discourage in the code. Because at the end of the end they both end up at the same path. However how they got that information is differently and I don't like to remember somewhere in memory each of those paths to give more accurate stats.

However I really like to get going on a FAQ and have such question added. 

> Fine, it is in the To Do list ?

I first have to discuss code-wise with @vednoc ;)

> But for the short place it take, show the year is more simple (in futur).

I will remember that when I refactor the cards.

**Comment by decembre** [comment]
<blockquote>That isn't really possible without going to remember each IP's visit of paths</blockquote>

Ok... but just make a calculation without remember anything to have a
Total Minimal views (never less than the number of installs)

By example:
0 views and 10 installs
mean at less:
10 views, no?

**Comment by Gusted** [comment]
> Total Minimal views (never less than the number of installs)

I would consider that lying to the user.

If in fact all users has already installed the style and are updating the style every day or so(stylus does this automatically), it's considered installing. However that doesn't mean they've visited the style's page and thus also should increase the view count.

> But, maybe it's difficult or not possible:
I am not programmer, you know ?

It's possible, but it's misrepresentation what the facts are.


Consider this scenario:

We have some popular bank.
This bank has a lot of customers, let say 80.000.
Because the bank only allow customers from this village(with a population of 80.000) they only have new customers when a new baby is born.

However, every day they also show on their site 2 stats:
- How many customers has made a transaction that day.
- How many new customers have signed a contract.

So having that said, consider that ~90% of the customers make daily a transaction.

Day 1: 

= Transactions 75.121
= New customers 0

Day 2:

= Transactions 78.324
= New customers 1


This is in fact a good representation of the stats, but for anybody it can seem off that they make a thousands of transactions daily but almost have zero to none new customers. I

f they would tell that that they have the same amount of new customers(or somewhere close) that would be straight out lying and misrepresenting what the facts actually are.

Because of that we won't do that.

**Comment by vednoc** [comment]
> Maybe add these "outside install" to the number of views should less confused for others

As it stands, we can't do that without adding additional logic to somehow "track" how the userstyle is being installed. If we added installs made via Stylus to the view count, imagine how confusing it would be to have, let's say 3000 views and 10 installs in total. If we made it 3010 installs, that would be lying. That's clearly the type of behavior that can be categorized as a bug by many.


> 0 views and 10 installs mean at less: 10 views, no?

Not necessarily. There's going to be an influx of installs when I change `@updateURL` on my other userstyles, yet those users will very likely never visit (or even know about) USw. It's up for a debate, but I believe that it's technically correct as-is. Sadly, USo and all userscript-equivalent sites don't offer view counters, so we're the first ones to actually do this.

Also what @Gusted said. The whole point of resetting our inaccurate statistics is to be correct about them. Our goal isn't about manipulating the data to satisfy the shareholders, but to provide insight in how many users use your userstyles.


> I first have to discuss code-wise with @vednoc ;)

I was thinking of how to handle it. We clearly need to remember last logged-in state, or the last time since someone's been on their dashboard, and make specific queries using that data. The latter is more accurate, but it might not be ideal if the user goes back in history, closes the page, or something along those lines. Either way, we'll have to bump updated_at field in the users table, or make an entirely new table to handle this functionality.

**Comment by decembre** [comment]
I agree

> It's up for a debate

I haven't the solution, but i feel it need something like calculation / explanation (notice) / formulation ( e.g. View on USw)....

**Comment by vednoc** [comment]
An explanation is definitely going to be added once FAQ page is made. Other than that, I'm all ears when it comes to improving it, but the numbers must not lie.

**Comment by vednoc** [comment]
Forgot to add a reference to this issue in the commit, so here is the FAQ: https://github.com/userstyles-world/userstyles.world/commit/8f2926202fd48633771aad54847b67fba9b4cc2b#diff-57cdcc6b6701a7ce3b3a8f8c0366e0e611e6fb1a1b8dd7cd29e3263b3e064c8bR48

**Comment by Gusted** [comment]
I've added some more clarification to this exact scenario, https://github.com/userstyles-world/userstyles.world/commit/f362007a02e56094e3d6b39458914cdb50dd7035
