### ISSUE TITLE
"Duplicate style" when adding or importing 34kb stylesheet

### ISSUE THREAD

**Issue by ozramos** [userstyles-world/userstyles.world#79]
- **Browser**: Latest Chrome on Windows
- **Screenshot**:
![image](https://user-images.githubusercontent.com/62826752/129135698-e6b9bca8-e717-4c87-b335-c69fcac6ebc0.png)

- **Additional context**:
Hi! I've been trying to upload my new Notion stylesheet but get that error. I tried both adding and importing from the Archive here: https://uso.kkx.one/style/210773

Could it be the filesize? I'm inlining 98.css and also Base64 a background image so the filesize is 34kb
Thanks!

**Comment by vednoc** [comment]
No, we don't have a limit on file size yet (although we should set it to _some_ value in order to prevent abuse). The issue was a (really bad) typo, and I wrote about the root cause here: https://github.com/userstyles-world/userstyles.world/commit/02a81019643a1d309c2e46be69baddc2b8c42a10

P.S. I should've looked at issues as well, but I'll add a reference to this issue in the changelog. Thank you for reporting the bug!
